### ISSUE TITLE
Feeds not working (or not exists)

### ISSUE THREAD

**Issue by aminmesbahi** [VahidN/DntSite#1]
Please check the RSS feed URI, I couldn't find new site's RSS URI within meta tags, sitemap, and source code fast checking

**Comment by VahidN** [comment]
Yes, It's a work in progress...

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/DntSite/commit/c99a7312c5e413fea46711e517cd2a821207ec42

**Comment by aminmesbahi** [comment]
![image](https://github.com/user-attachments/assets/72d95f7c-ce08-4209-baa7-99355e1e2a61)

**Comment by shaahink** [comment]
> ![image](https://private-user-images.githubusercontent.com/866928/352871838-72d95f7c-ce08-4209-baa7-99355e1e2a61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjU4OTIsIm5iZiI6MTcyMjIyNTU5MiwicGF0aCI6Ii84NjY5MjgvMzUyODcxODM4LTcyZDk1ZjdjLWNlMDgtNDIwOS1iYWE3LTk5MzU1ZTFlMmE2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwMzU5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzQzYzU5NTA2OGU3NWEwYjMzNzQ1YzgwOWEwOGM3ODI0NGM0YThmNWNlNWQ0OTRjMjYzMTc1NWRkMDlmNWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j9kkM73pb0oFkdfsTdh1SBeNs87LLmxqRi_LsTUmuxc)

Give it another go, working fine on my end:

![image](https://github.com/user-attachments/assets/be2410a3-c6d8-4698-845a-5824f98e9d34)

**Comment by VahidN** [comment]
There are some minor feed validation issues here, I will fix them today.

**Comment by VahidN** [comment]
[It's validated](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.dntips.ir%2Frss.xml)
