### ISSUE TITLE
Save As Draft Before Posting New Topic

### ISSUE THREAD

**Issue by CesSolutions** [VahidN/DntSite#10]
Hello

### Suggestion:
Add new button to save text as **Draft** for long text. Some text may take more time to be complete for posting.

Thanks

**Comment by CesSolutions** [comment]
I made a mistake in title: 
Tip (Wrong) => Topic (Correct)

**Comment by CesSolutions** [comment]
I made a mistake in title: 
Tip (Wrong) => Topic (Correct)

**Comment by VahidN** [comment]
We already have this feature. All of the new posts should be stored as draft and verified before being approved and published.
