### ISSUE TITLE
Return to Last Page After Login

### ISSUE THREAD

**Issue by CesSolutions** [VahidN/DntSite#11]
Hello

Now, when user log into account, must navigate to last page where he was studying. It is better to return back to last page automatically.

Thanks

**Comment by VahidN** [comment]
[It does](https://github.com/VahidN/DntSite/blob/main/src/DntSite.Web/Features/UserProfiles/Components/Login.razor.cs#L84), and ... when a page doesn't require authentication, there will be no redirect after login for it.

**Comment by CesSolutions** [comment]
### Just as a suggestion:

Create login page like modal/popup window. So, when user click on **"Login"** item, then after successful authentication , user just need to refresh current page to be authorized to do any action and dose not need to navigate web site to reach the last page.

**Comment by CesSolutions** [comment]
Thanks a lot
