### ISSUE TITLE
UI Compact Mode

### ISSUE THREAD

**Issue by CesSolutions** [VahidN/DntSite#17]
Hello

### Suggestion

In the suggested UI design changes are as follow:

1. Narrower `Title Bar` at the top of page.
2. Locate `Dark Mode` option in title bar.
3. Show title of topics with publish time but, without main text. In this mode more title can be seen by user.
4. A tick next to title of topics can show that topics is closed and final answer approved (For questions).

Thanks

![Suggested  Desktop Theme](https://github.com/user-attachments/assets/703cb8d4-4750-4c6a-ba1f-edf83ff66b07)

![Suggested  Mobile Theme](https://github.com/user-attachments/assets/6c5820f9-e0a3-415d-8314-1b73baee574d)

**Comment by VahidN** [comment]
I have to no intention to change anything about these topics. If this site makes you unhappy, just leave.
I will ban your user. You are not helpful and you are wasting my time.
