### ISSUE TITLE
OS recognition in Online user section

### ISSUE THREAD

**Issue by davmszd** [VahidN/DntSite#18]
My OS has been recognized  incorrectly in the online user section.

![image](https://github.com/user-attachments/assets/518c0340-65ce-4da1-8ba2-376b12080aca)

![image](https://github.com/user-attachments/assets/53513124-f381-4a6f-82d0-c090a504d322)

**Comment by davmszd** [comment]
Just to clarify, the Chrome version was recognized correctly.

![image](https://github.com/user-attachments/assets/27d6fe53-8f02-40ed-91e6-f177c201df38)

**Comment by VahidN** [comment]
Yes, I Know and [it's explained here](https://www.dntips.ir/post/3460#comment-19371). It should be reported and [fixed here](https://github.com/ua-parser/uap-core).
