### ISSUE TITLE
ویرایش پست‌ برای همه کاربران فعال است

### ISSUE THREAD

**Issue by MehdiSaeedifar** [VahidN/DntSite#5]
ویرایش پست برای همه کاربران فعال است در صورتی که هر کاربر فقط باید بتواند پست خودش را ویرایش کند

![Screenshot 2024-08-03 133432](https://github.com/user-attachments/assets/f640c5cc-bafb-469f-8794-d2fb6ca28473)

**Comment by VahidN** [comment]
Thank you. Fixed it via #https://github.com/VahidN/DntSite/commit/b026a5cd1f44c5cf12c4755fb44a146203b6421c
