### ISSUE TITLE
باز کردن یک لینک در ایمیل

### ISSUE THREAD

**Issue by mammadkoma** [VahidN/DntSite#6]
با سلام ، وقتی یک ایمیل میاید برایم و حاوی متن آخرین مطالب ارسالی و یک لینک است و روی اون لینک کلیک میکنم و وارد مقاله لینک میشوم با اینکه در سایت لاگین کرده بودم اسمم رو بالای سایت در هدر نمینویسه و نمیشه در مقاله کامنت گذاشت.

**Comment by VahidN** [comment]
[مشكل را اينجا توضيح دادم](https://www.dntips.ir/post/2520#comment-19353)
